### ISSUE TITLE
Show history of archived toggles?

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-frontend#115]
It would be nice to see the change history of a archived toggle. 

What do you think @corinnekrych ?

**Comment by corinnekrych** [comment]
Agreed @ivarconr we could rework the archive page to get it better.

I think we should have a dedicated page to show archived feature (it would fit material design better). It would be nice to reuse the feature display in read-only mode. Out of the 3 tabs: metrics, edit, history, we could display: edit (renamed Strategies) and history. 
If we want to display history, we'll need to fetch the history as the archive endpoint does not return it in the payload.
https://github.com/Unleash/unleash/blob/master/docs/api/admin/feature-toggles-api.md#archive 

Some interesting refactoring is needed for re-using the page.
I can pick up that issue :)

**Comment by ivarconr** [comment]
A dedicated read-only view makes sense. There is already an issue on cleaning up the landing page for active toggles: https://github.com/Unleash/unleash-frontend/issues/78

For the history tab I think the existing component with the current container wrapper will just work as it already uses the events API:

http://unleash.herokuapp.com/api/admin/events/TEST
