### ISSUE TITLE
Add application validations

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-frontend#15]
input for colors + validation
input for icons + validation

**Comment by sveisvei** [comment]
I have collected all the icons in a list, but unsure how to present the selection.

**Comment by ivarconr** [comment]
Use the autocomplete from react-mdl-extra?

![image](https://cloud.githubusercontent.com/assets/158948/21544613/dc25d10a-cdd0-11e6-8601-2af2fbb41836.png)




https://hribb.github.io/react-mdl-extra/?selectedKind=AutoComplete&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel
