### ISSUE TITLE
Feature Toggle list: add "seen appname" sort

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-frontend#16]

**Comment by sveisvei** [comment]
How should this one work? Is it really needed? 

Would require to fetch seen-apps for all toggles so we can sort on appname.

**Comment by ivarconr** [comment]
You might have a point. The initial idea is that people tend to work in one app, and only care about toggles inside that app. This can now be achieved via the app view, and this might be sufficient for now. 

It might be better to add this as an extra meta info when creating a toggle. Then you can say "I intend to use this toggle in AppX" which is more accurate than basing it on metrics reported by an app (we will not be able to see toggles that is not part of a code path in the app). This will also move toward a more robust solution to allow apps to only query toggles intended for them.

**Comment by ivarconr** [comment]
closing for now. Can reopen if we change our mind!
