### ISSUE TITLE
Update description cleared during edit

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-frontend#168]
When you try to edit the toggle description the value is cleared every time the background poller has fetched updated toggle metrics.

**Comment by dustinbarnes** [comment]
YES! I just ran into this issue today. It seems that the description edit gets posted, but the in-memory model isn't updated. Then, when you click the "update" button, it sends a stale description to the server. 

This seems to be worked around by "just" waiting a couple seconds after tabbing out of the description field before pressing update. Would be nice if this could get a fix!

**Comment by ivarconr** [comment]
thanks for reminding me, this has not bothered me to much lately, but will try to put in a fix soon.
