### ISSUE TITLE
NPM module v2.3.5 broken

### ISSUE THREAD

**Issue by dustinbarnes** [Unleash/unleash-frontend#179]
It got resolved via npm. Using the no-auth mode of Unleash, whenever it loads up the features page, it errors out with this in the console: 

```
TypeError: "h.slice(...).map is not a function
```

Given the nature of the bundle, it's on line 1 :). Is this an off release, or was some other dependency updated accidentally?

**Comment by ivarconr** [comment]
Thanks for reporting. I assume you are talking about version "3.2.5".

**Comment by dustinbarnes** [comment]
Yes, I was talking about 3.2.5, sorry for the mixup. I fixed the title. 

My version is branched from master, here's my reflog: 

```
[10:19:30] dbarnes in ~/ws/unleash-lp/unleash on lp-db-changes [!?]
$ git reflog
47bef01 (HEAD -> lp-db-changes, origin/lp-db-changes) HEAD@{0}: cherry-pick: Unleash#316 Migrating migration-files to knex-js
54080fe (origin/master, origin/HEAD, master) HEAD@{1}: checkout: moving from master to lp-db-changes
54080fe (origin/master, origin/HEAD, master) HEAD@{2}: clone: from git@github.com:dustinbarnes/unleash.git
```
I am taking a stab at moving some more of the postgres-specific stuff to knex, that's the cherry-pick that my head is pointing to. I've mostly got it running on sqlite3, just trying to deal with some of the default-value issues with the knex driver.

**Comment by dustinbarnes** [comment]
Another update: I now believe this is due to the frontend code expecting default values as specified in the DB. sqlite3 doesn't do so good with that, so some of the values were, for example, null instead of an empty array. Additionally, the sqlite3 driver does not automatically convert json fields to actual json objects, so it was treating them as opaque strings. 

Closing due to PEBKAC.
