### ISSUE TITLE
Improve visual presntation of "History view"

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-frontend#19]

**Comment by ivarconr** [comment]
It also looks a bit old when you "enabled/disables" a toggle and it is not directly updated in the history tab of a feature toggle.

**Comment by sveisvei** [comment]
In general we should just make the data-fetching via a socket with events, or else its just monkeypatching imo.

**Comment by ivarconr** [comment]
Yes in a perfect world. Will require some extra work on the API, and I want
to do that, but not as part of this issue.
