### ISSUE TITLE
Some way to add multiple list entries at a time

### ISSUE THREAD

**Issue by glasser** [Unleash/unleash-frontend#222]
I've got a file with a list of user IDs. I'd like to add them all to a toggle. I don't think the frontend lets me do that? I have to type one by one, right? Or use the API somehow?

**Comment by glasser** [comment]
Heh, I guess entering them comma-separated works, though there's no way to figure that out other than understanding how they are eventually encoded.

**Comment by ivarconr** [comment]
Hi @glasser, yes I agree that this is not super intuitive. 

How do you think we can improve the input field? 

Also, there exists API endpoints to update feature toggle configuraton:
https://unleash.github.io/docs/api/admin/features#update-a-feature-toggle

**Comment by glasser** [comment]
I expected that perhaps pasting a newline-separated string would work, but it does not.

The ability to upload a newline-separated file might be nice too.

I'm aware of the API endpoint but (a) even as a developer, getting auth set up is a pain and (b) we want this to be accessible to non programmers on our team as well.
