### ISSUE TITLE
Feature Request: add last use timestamp

### ISSUE THREAD

**Issue by nnorwitz** [Unleash/unleash-frontend#226]
As an unleash flag goes through its life-cycle, we need to determine when it is safe to archive a flag.  Having the last time the flag was referenced would be a big help to avoid investigating.

The last minute/last hour tickers are useful for active flags.  For inactive flags, the last used timestamp is more useful.

Sorry if I missed this.  I looked around in the history and other places to see if this information was available.

Anywhere on the /#/features/view/XXX page would be fine.

**Comment by ivarconr** [comment]
Thanks, this is a great suggestion. 

Could you move this to https://github.com/Unleash/unleash, as it should be available from the API as well?

Also, I think it would be fare to call frame it as `lastSeenAt`, as client SDKs may opt out of sending metrics back to the server, and thus not showing actual usage. 

What do you think?

**Comment by nnorwitz** [comment]
https://github.com/Unleash/unleash/issues/642

I agree with everything you suggested.  Feel free to close this or leave it open, whichever works better for you.

Thanks for your consideration.
