### ISSUE TITLE
Clarification about "Strategies Constrains"

### ISSUE THREAD

**Issue by Falci** [Unleash/unleash-frontend#228]
I found this test/specification: 
https://github.com/Unleash/client-specification/blob/0b857978401e7ebaeddfbaee9fc57faef9741b00/specifications/09-strategy-constraints.json#L6-L24

Not sure how can I create such condition using Unleash UI.

Also, looking in the code I found some routes that are apparently unliked.
https://github.com/Unleash/unleash-frontend/blob/87fbccef3e9ff33ddf4183fe0e70835f00d85015/src/component/menu/routes.js#L51-L59

**Comment by ivarconr** [comment]
Hi @Falci,

> Not sure how can I create such condition using Unleash UI.

I know it can be confusing, as the frontend is shared between Unleash Open-Source and Unleash-enterprise. 

Strategy constraint is currently an Unleash-enterprise feature. Part of our effort to grow and expand Unleash to become the leading Open Source Feature toggle system, we continuously evaluating what features will be Enterprise and OSS. I hope we soon can land on a official definition on what belongs in OSS and Enterprise, to provide better exceptions. 

The way, for now, to make use of custom context fields, is to use [custom activation strategies](https://unleash.github.io/docs/guides/custom_activation_strategy).
