### ISSUE TITLE
Archived toggle is suggested to be created from `/applications`

### ISSUE THREAD

**Issue by SimenB** [Unleash/unleash-frontend#249]
I created a toggle, used it in an app, then archived the toggle. Now navigating to `/#/application/my-app` says 
![image](https://user-images.githubusercontent.com/1404810/109619231-d103bc00-7b38-11eb-82a5-e7deee75dc5e.png)

which links to `#/features/create?name=asdasd`. However, Unleash knows this is an archived toggle on `/#/archive`: 
![image](https://user-images.githubusercontent.com/1404810/109619295-e678e600-7b38-11eb-8c3b-4e7c3abbfe3d.png)

I'd expect the application page to know the toggle has been archived

**Comment by FredrikOseberg** [comment]
This was fixed as a part of the v4 release.
