### ISSUE TITLE
Detected Locale is Broken in Safari

### ISSUE THREAD

**Issue by dshafik** [Unleash/unleash-frontend#265]
In Safari, `navigator.language` returns lowercase values, e.g. `en-us`, which doesn't match the `en-US` local, leading to an unknown locale.

**Comment by FredrikOseberg** [comment]
> In Safari, `navigator.language` returns lowercase values, e.g. `en-us`, which doesn't match the `en-US` local, leading to an unknown locale.

Thanks for reporting. We'll get a fix up for this as soon as possible.
