### ISSUE TITLE
Going back from a toggle should keep scroll position

### ISSUE THREAD

**Issue by SimenB** [Unleash/unleash-frontend#27]
Unleash/unleash#190

**Comment by ivarconr** [comment]
Tried https://github.com/taion/react-router-scroll and even set a custom `ScrollContainer`, but still not working. Suggestions?

**Comment by SimenB** [comment]
Seems like it should Just Work ™️ ReactTraining/react-router#1686
Is data always fetched even though it's already in redux store? It seems like it needs a synchronous first render (or SSR)

**Comment by ivarconr** [comment]
yes, its already in the store and should render with that content first. It will also try to to a toggles fetch, just to see if there is some changes to any toggles.

**Comment by sveisvei** [comment]
it wont work until you remove my scroll-to-top-stuff in app.js
