### ISSUE TITLE
Encoding issue when setting username cookie

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-frontend#39]
should user `encodeURIComponent(str);` when setting cookie value to avoid charset issues!

**Comment by ivarconr** [comment]
@sveisvei solves the encoding issue, but will not fix already set cookies, they must renter username.

**Comment by sveisvei** [comment]
![skjermbilde 2017-01-14 kl 14 01 28](https://cloud.githubusercontent.com/assets/121438/21955021/137a8c8e-da62-11e6-954d-436721e40206.png)
