### ISSUE TITLE
Index page infinite reload loop when not logged in

### ISSUE THREAD

**Issue by dkappBTO** [Unleash/unleash-frontend#451]
I modified unleash server (per docs) to used the Google OAuth middleware. However, when the root url is loaded loaded in a browser the frontend just reloads in an infinite loop. I tried adding a 1 sec delay in the server's 401 response but it doesn't seem to help any sort of race condition.

https://user-images.githubusercontent.com/92392501/138158829-d458a69a-43c6-4444-9367-887318dd8acd.mov

**Comment by ivarconr** [comment]
Yes indeed! And it should be fixed in the latest master. Btw, you should
probably not use the latest master, but instead rely on the latest
published version, e.g. v4.1.5.
