### ISSUE TITLE
Move github link and username into menu

### ISSUE THREAD

**Issue by vsandvold** [Unleash/unleash-frontend#47]
I suggest we move the github link and username from the header into the menu drawer. It will clean up and make more space in the header for other, perhaps more important elements.

Suggestion:
![fireshot capture 205 - unleash admin - http___localhost_3000_ _features_view_asdfasdf](https://cloud.githubusercontent.com/assets/6734787/22040207/6076d586-dd02-11e6-88f0-ad65f71b540e.png)

**Comment by sveisvei** [comment]
Sure thing, wfm - but the username might be in place also - imo. But not important now - we support richer profile-data (name + image) etc via Okta soon as well maybe?

**Comment by vsandvold** [comment]
No prob, I can leave the username where it is now. A logo would be nice too, at the top of the menu drawer :-)

**Comment by SimenB** [comment]
👍 Please call it "GitHub" as well
