### ISSUE TITLE
Simplify header title

### ISSUE THREAD

**Issue by vsandvold** [Unleash/unleash-frontend#48]
The header title can be simplified, retaining only the section name corresponding to the selected menu item. This section name (as a link) will enable navigation back to the section top from eg. a specific feature toggle or strategy. The name of the feature toggle or strategy itself can be shown in the page content.

Suggestions:
![fireshot capture 206 - unleash admin - http___localhost_3000_ _features](https://cloud.githubusercontent.com/assets/6734787/22040602/a8fb374c-dd03-11e6-8ed1-fce4e45d5436.png)
![fireshot capture 207 - unleash admin - http___localhost_3000_ _history](https://cloud.githubusercontent.com/assets/6734787/22040603/a9153ba6-dd03-11e6-8d8c-b7269eaa47c7.png)

**Comment by sveisvei** [comment]
What should it show when inside level 2 and level 3? e.g. inside a toggle-view / create-toggle-view

**Comment by vsandvold** [comment]
The section title ("Feature toggles") should work for level 2 pages like the toggle view, also as navigation back to the toggle list. May not be entirely conventional, though. Level 3 pages like the create toggle view (I didn't know that) could also be shown as modal dialogs, much like opening up an email in Google inbox (on mobile). What do you think?

**Comment by ivarconr** [comment]
It's definitely more clean, but I would like to settle a strategy for level 3 before moving in this direction!

**Comment by vsandvold** [comment]
I can just do away with the first "Unleash" link for now, if there's no special reason to keep it around? That will help a little :-)

**Comment by sveisvei** [comment]
released updated version and deployed http://unleash-master.herokuapp.com
