### ISSUE TITLE
Can't create feature from "Application overview"

### ISSUE THREAD

**Issue by lmorel3** [Unleash/unleash-frontend#485]
Hi,

Since the latest version of the app, it's impossible to create an issue from the "Application overview", when the issue is tagged as missing.
Indeed, when I click on the missing feature's name, I'm well redirected to the creation page, but I can't submit the form.

It's due to the "projectId" provided in the URL : `/projects/undefined/create-toggle?name=MISSING_FEATURE_NAME`.
There's an issue because we can't choose the "Project" anymore when we create a new feature, since it should already be known.

In this case, it would be great if we can choose the project. What's your opinion ?

Regards,

**Comment by ivarconr** [comment]
Hi there, 

yes indeed it should not use `undefined` but rather fallback to the default project and allow you to choose a different project at will. Makes sense!

**Comment by FredrikOseberg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Unable to create feature toggle from application view.](https://trello.com/c/0VRJVG7D/581-bug-unable-to-create-feature-toggle-from-application-view)

**Comment by ivarconr** [comment]
For reference, it only makes sense to select project in a commercial version of unleash which supports more than the default project. 

When the project feature is accessible you get it, but it selects "undefined" which is silly:

![image](https://user-images.githubusercontent.com/158948/139951863-e2680d91-767a-4a95-b4d2-6a83ec73e297.png)

**Comment by lmorel3** [comment]
> For reference, it only makes sense to select project in a commercial version of unleash which supports more than the default project.

Sure. I didn't specify I'm not using the commercial version. Sorry :)

**Comment by ivarconr** [comment]
nothing to feel sorry about, we have open-source Unleash because we want people to use it and get value out of it. This is still a bug we want to fix.
