### ISSUE TITLE
Improved page layout

### ISSUE THREAD

**Issue by vsandvold** [Unleash/unleash-frontend#49]
Minor adjustments to the layout, grid and use of shadows may highlight the important content and give us some interesting opportunities for placement of eg. floating action buttons.

Suggestion:
![fireshot capture 210 - unleash admin - http___localhost_3000_ _features](https://cloud.githubusercontent.com/assets/6734787/22041532/87b0c5e4-dd07-11e6-9946-7b6c761fbf7a.png)

**Comment by ivarconr** [comment]
looks better!
