### ISSUE TITLE
New feature toggle page layout

### ISSUE THREAD

**Issue by vsandvold** [Unleash/unleash-frontend#50]
Desktop:
![fireshot capture 199 - unleash admin - http___localhost_3000_ _features_view_asdfasdf](https://cloud.githubusercontent.com/assets/6734787/22041592/bcf5a9f4-dd07-11e6-8f17-12bac06516b9.png)

Mobile:
![fireshot capture 200 - unleash admin - http___localhost_3000_ _features_view_asdfasdf](https://cloud.githubusercontent.com/assets/6734787/22041604/c71d4a4a-dd07-11e6-992f-d40c9b198b90.png)

**Comment by ivarconr** [comment]
This is definitely better than our current implementation. See no reason not to move in this direction.

**Comment by sveisvei** [comment]
This improvement is a no-brainer indeed.
