### ISSUE TITLE
Toggle "Created Invalid Date"

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-frontend#59]
Because of the changed UI we need to make sure to set the created data when creating a new toggle (this is automatically set by the api if missing).

By not setting it in the ui we get state issue:

![ffb505a6-e4d1-11e6-8704-b99d469d9798](https://cloud.githubusercontent.com/assets/158948/22402534/213c9d86-e5fb-11e6-891e-167eabad93e4.png)

Also we get history issue, because it is set after it is actually created:

![2017-01-29-081942_763x257_scrot](https://cloud.githubusercontent.com/assets/158948/22402558/be68489e-e5fb-11e6-8524-a2d88c8c3650.png)

(this issue also related to https://github.com/Unleash/unleash/issues/205)

**Comment by vsandvold** [comment]
Maybe we can just remove the created date form this view? I'm not familiar with the use case, but you should be able to find it at the very start of the history.

**Comment by ivarconr** [comment]
yes, i think I will have a go on this one, it might require changes in both the API and the UI.

**Comment by vsandvold** [comment]
Ah, it's more complicated than I thought. I didn't see the history issue until now :-)
