### ISSUE TITLE
Viewer role cannot view parameters for a strategy

### ISSUE THREAD

**Issue by brandontuttle** [Unleash/unleash-frontend#644]
When a user is configured as a Viewer, they are unable to view the details of a strategy. Instead, it looks like there are no details defined for that strategy. This data does come back through the API for that role.

Viewer:
![image](https://user-images.githubusercontent.com/68201364/151612218-fe10fe78-4e70-49b6-868e-6b799583d501.png)

Admin/Editor:
![image](https://user-images.githubusercontent.com/68201364/151612241-1330e21f-2c79-45ca-8ea1-205809ecaff9.png)

**Comment by ivarconr** [comment]
Thanks for reporting this @brandontuttle 👍🏼 

I have created a PR to address the issue: https://github.com/Unleash/unleash-frontend/pull/645
