### ISSUE TITLE
Time is one hour off

### ISSUE THREAD

**Issue by SimenB** [Unleash/unleash-frontend#71]
![image](https://cloud.githubusercontent.com/assets/1404810/23253635/8f7b191c-f9b5-11e6-98b0-02ff056f599b.png)
 Time is now 10:48

**Comment by ivarconr** [comment]
I can not reproduce this locally or at heroku. This timestamp is set directly in DB, it might be that the DB-server you are running on is one hour off? I can check it in FINN tomorrow.

**Comment by SimenB** [comment]
https://github.com/tgriesser/knex/issues/1085

**Comment by SimenB** [comment]
![image](https://cloud.githubusercontent.com/assets/1404810/23380693/13b5bd5c-fd3c-11e6-8930-89ef28ef90d9.png)

^ that is weird... @ivarconr, it's `kubernetes.loadbalance.legacy.mfinn` if you wanna take a look at it

**Comment by ivarconr** [comment]
solved in unleash-server
