### ISSUE TITLE
"Landing page" for toggles should contain info about the toggle

### ISSUE THREAD

**Issue by SimenB** [Unleash/unleash-frontend#78]
Right now if I click a toggle from the list, the "landing page" is "metrics". To see the value of the toggle, I have to go to either "history" or "edit". I would prefer to either see a new tab with info about the toggle, or this info added above metrics.

![image](https://cloud.githubusercontent.com/assets/1404810/23750103/b3b4c0fa-04cb-11e7-9d26-358c27cf4cea.png)

The only info I get ^ is what strategy it uses. Useful info is hidden in "edit".

![image](https://cloud.githubusercontent.com/assets/1404810/23750134/cdf8cbbe-04cb-11e7-8923-0f288be964c6.png)

I want a read-only view of ^

**Comment by vsandvold** [comment]
I agree, we could try to show the three tabs as sections underneath each other, more like a dashboard. Strategies first perhaps, and then metrics and history last.
