### ISSUE TITLE
Event history should include name of toggle

### ISSUE THREAD

**Issue by SimenB** [Unleash/unleash-frontend#79]
Name is missing, so I have to view full event in order to see which toggle got changed

![image](https://cloud.githubusercontent.com/assets/1404810/25614741/8623b7ee-2f33-11e7-8083-c45d471d9fe8.png)

**Comment by SimenB** [comment]
Also, archived toggle looks weird

**Comment by ivarconr** [comment]
yes, should be fixed. Dunno why archive looks so strange, might be that it does some cleanups it should not do (should only disable & archive it)...

**Comment by SimenB** [comment]
almost 2 years later 😀
