### ISSUE TITLE
Admin UI changes to support AND/Groups

### ISSUE THREAD

**Issue by vsandvold** [Unleash/unleash-frontend#81]
Accompanying changes to the strategies protocol https://github.com/Unleash/unleash/issues/229

The admin UI must support configuration of toggles with groups of strategies. This will be a redesign of the current Edit tab on the feature toggle page.

Possible groupings include:

- environment (dev/prod)
- device (mobile/desktop) 
- user type (anonymous/logged in)
- application
- strategies

First deliverable will be a selection of design proposals.

**Comment by ivarconr** [comment]
👍

**Comment by vsandvold** [comment]
I don't know how much work it will be in the end, but it may be good to reduce the scope of this task for the 3.0 release. We could focus on the dev/prod environment grouping as a first iteration, solving what we know is a clear need in FINN today. Then we can go on an investigate the other grouping alternatives in subsequent releases.

The UI for prod/dev can be easily fixed by removing the tabs for metrics/edit/history (and showing them on one page as suggested in #78) and adding tabs for prod/dev instead. That will give us a clean and conventional UI without much need for extra development.

It would also be good to address some short-comings reported by users for the 3.0 release:
- #79 
- #19 
- #84 
- https://github.com/Unleash/unleash/issues/249
- https://github.com/Unleash/unleash/issues/204
- https://github.com/Unleash/unleash/issues/209
 
What do you think?

**Comment by ivarconr** [comment]
I agree we should limit the scope and try to solve real use-cases. I belive solving the format suggested in https://github.com/Unleash/unleash/issues/229 is the most important part to get right, making the underlaying format flexible with regards to grouping.

We can add just whats needed in the UI in the first iteration, and then iterate improvements over time.
