### ISSUE TITLE
Long text goes out of the box

### ISSUE THREAD

**Issue by Edgar56** [Unleash/unleash-frontend#917]
### Describe the bug

Long text doesn't fit in the box of strategy parameter

### Steps to reproduce the bug

1. Create custom strategy with paramater list
2. Add into list long text e.g. file path 
3. Click on save
4. Add strategy to one of your toggles
5. Expand the feature toggle
Actual result:
Long text goes out of the box and also not possible to remove from the list

### Expected behavior

Text should fit in the box (container)

### Screenshots

![16511580316081550386338976877472](https://user-images.githubusercontent.com/15981617/165782722-4dc8329a-a889-460c-9865-3e7b2e357ff6.jpg)
![16511580494156497173705914769928](https://user-images.githubusercontent.com/15981617/165782768-608513d4-eb71-44bb-a149-ed59662c0ff0.jpg)

### Unleash version

4.10.0

**Comment by thomasheartman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GitHub bug report (frontend): long text overflows its box ("CSS is awesome")](https://trello.com/c/zfsGDnWA/1100-github-bug-report-frontend-long-text-overflows-its-box-css-is-awesome)

**Comment by Edgar56** [comment]
When it will be fixed ?

**Comment by thomasheartman** [comment]
Hey, @Edgar56! 🙋🏼 Thanks for raising this. We triaged this in the standup today. Its been assigned and we'll probably look into it rather shortly, but I can't give you any specific date or time.

Regarding your last point in the reproduction steps:
> Long text goes out of the box and also not possible to remove from the list

It looks like the "X" button is there in edit mode (your second screenshot). Does it work to remove it from that view? For reference, you _shouldn't_ be able to remove an item from the view mode (your first screenshot).

**Comment by Edgar56** [comment]
Yes I can remove it from edit mode :)
