### ISSUE TITLE
Unleash version in UI

### ISSUE THREAD

**Issue by leftieFriele** [Unleash/unleash-frontend#97]
It would be really useful to have the unleash server version somewhere in the UI.

**Comment by ivarconr** [comment]
Yes that would be nice. 

Currently you can see the version in the index API endpoint:
`http://unleash.herokuapp.com/api/`

![image](https://user-images.githubusercontent.com/158948/33177882-74d79118-d064-11e7-92b8-a01383328ae7.png)

**Comment by ivarconr** [comment]
Released as part of `unleash-server:3.0.0-alpha.6`
